* My dwm hacks

My patches and hacks to [[https://dwm.suckless.org/][dwm]].

Patching guide: https://dwm.suckless.org/customisation/patches_in_git/.

** Branches

=main= is my default branch, containing my hacks and patches.

=master= tracks upstream [[http://git.suckless.org/dwm/][dwm]].

** Updates

Merge upstream updates to [[https://dwm.suckless.org/][dwm]]:

#+begin_src sh
  git checkout master
  git remote add upstream git://git.suckless.org/dwm
  git fetch upstream
  git merge upstream/master
#+end_src

Merge updates into feature branch:

#+begin_src sh
  git checkout master
  git pull -v --all
  git checkout <feature-branch>
  git rebase --preserve-merges master
  ... fix merge conflicts ...
  git rebase --continue
  git push origin
#+end_src

Pull-request feature branch against =main=.

** Install

#+begin_src sh
  git checkout main
  make
  sudo make install
#+end_src

** Test

#+begin_src sh
  startx -- /usr/bin/Xephyr -screen 2560x1440 :1
#+end_src

** Patches

*** modkey

Change modkey to Super.

#+begin_src sh
  /* key definitions */
  #define MODKEY Mod4Mask
#+end_src

*** noborder

- https://dwm.suckless.org/patches/noborder/

Remove border on single visible window, fixed version.

#+begin_src sh
  wget https://dwm.suckless.org/patches/noborder/dwm-noborderfloatingfix-6.2.diff
  git apply dwm-noborderfloatingfix-6.2.diff
#+end_src

*** three column

- https://dwm.suckless.org/patches/three-column/

Three-columns with centered master, for widescreen monitor.

#+begin_src sh
  wget https://dwm.suckless.org/patches/three-column/tcl.c
#+end_src

Replace =layout()= in =config.h=:

#+begin_src c
  #include "tcl.c"
  static Layout layout[] = {
          /* symbol               function */
          { "[T]", tile }, /* first entry is default */
          { "[F]", floating },
          { "[M]", monocle },
          { "[C]", Tcl },
  };
#+end_src

Add keybinding in =keys[]=:

#+begin_src c
  { MODKEY,                       XK_c,      setlayout,      {.v = &layouts[3]} },
#+end_src

*** classtitle

Modify first statement in =updatetitle()= to use short window CLASS
rather than full TITLE in the statusbar:

#+begin_src c
-	if (!gettextprop(c->win, netatom[NetWMName], c->name, sizeof c->name))
-		gettextprop(c->win, XA_WM_NAME, c->name, sizeof c->name);
+       gettextprop(c->win, XA_WM_CLASS, c->name, sizeof c->name);
#+end_src

*** appearance

Appearance mods: border, font and colour.

#+begin_src c
  static const unsigned int borderpx  = 3;        /* border pixel of windows */
  static const char *fonts[]          = { "xos4 Terminus:size=12" };
  static const char dmenufont[]       = "xos4 Terminus:size=12";
  static const char col_black[]       = "#000000";
  static const char col_green[]       = "#98fb98"; /* PaleGreen */
  static const char *colors[][3]      = {
          /*               fg         bg         border   */
          [SchemeNorm] = { col_gray3, col_black, col_black },
          [SchemeSel]  = { col_green, col_black, col_gray2 },
#+end_src

*** colemak

Extra movement keys for Colemak home row.

#+begin_src c
	{ MODKEY,                       XK_n,      focusstack,     {.i = +1 } },
	{ MODKEY,                       XK_e,      focusstack,     {.i = -1 } },
#+end_src

*** movestack

- https://dwm.suckless.org/patches/movestack/

Move clients around in the stack.

This patch doesn't apply, but extract the file =movestack.c= from the [[https://dwm.suckless.org/patches/movestack/dwm-movestack-6.1.diff][diff]].

Add include in =config.h=:

#+begin_src c
  #include "movestack.c"
#+end_src

Add keybindings in =config.h=:

#+begin_src c
  { MODKEY|ShiftMask,             XK_j,      movestack,      {.i = +1 } },
  { MODKEY|ShiftMask,             XK_k,      movestack,      {.i = -1 } },
  { MODKEY|ShiftMask,             XK_n,      movestack,      {.i = +1 } },
  { MODKEY|ShiftMask,             XK_e,      movestack,      {.i = -1 } },
#+end_src

*** pertag

- https://dwm.suckless.org/patches/pertag/

Keep layout per tag, instead of changing globally.

#+begin_src sh
  wget https://dwm.suckless.org/patches/pertag/dwm-pertag-20200914-61bb8b2.diff
  git apply dwm-pertag-20200914-61bb8b2.diff
#+end_src
